- project:
    templates:
      - openstack-specs-jobs
    check:
      jobs:
        - openstack-tox-pep8
        - openstack-tox-py37
    gate:
      jobs:
        - openstack-tox-pep8
        - openstack-tox-py37
